const ThemeImages = {
    "Minecraft": "themes/minecraft.png",
    "Star Wars": "themes/starwars.png",
    "Star Wars Episode 1": "themes/starwars.png",
    "Star Wars Episode 2": "themes/starwars.png",
    "Solo": "themes/starwars.png",
    "Star Wars Rogue One": "themes/starwars.png",
    "Star Wars Rebels": "themes/starwars.png",
    "Star Wars Episode 4/5/6": "themes/starwars.png",
    "Star Wars Episode 7": "themes/starwars.png",
    "Star Wars Episode 8": "themes/starwars.png",
    "Mini": "themes/starwars.png",
    "Ultimate Collector Series": "themes/starwars.png",
    "Jungle": "themes/cityjungle.png",
    "Police": "themes/citypolice.png",
    "Promotional": "themes/promotional.png",
    "LEGO Brand Store": "themes/promotional.png",
    "Ninjago": "themes/ninjago.png",
    "Ninjago The Movie": "themes/ninjagomovie.png",
    "Creator": "themes/creator.png",
    "Early Creator": "themes/creator.png",
    "Creator 3-in-1": "themes/creator.png",
    "Creator Expert": "themes/creator.png",
    "Modular Buildings": "themes/creator.png",
    "Sculptures": "themes/creator.png",
    "Creature": "themes/creator.png",
    "Basic Model": "themes/creator.png",
    "Friends": "themes/friends.png",
    "Animals": "themes/friends.png",
    "Classic": "themes/classic.png",
    "Cars": "themes/cars.png",
    "Architecture": "themes/architecture.png",
    "LEGO Ideas and CUUSOO": "themes/ideas.png",
    "City": "themes/city.png",
    "Town": "themes/creator.png",
    "Traffic": "themes/city.png",
    "Fire": "themes/city.png",
    "Space Port": "themes/city.png",
    "Coast Guard": "themes/city.png",
    "Train": "themes/city.png",
    "Hospital": "themes/city.png",
    "Monster Fighters": "themes/monsterfighters.png",
    "Arctic": "themes/arctic.png",
    "Nexo Knights": "themes/nexoknights.png",
    "Harry Potter": "themes/harrypotter.png",
    "Harry Potter and Fantastic Beasts": "themes/harrypotter.png",
    "Hidden Side": "themes/hiddenside.png",
    "Toy Story": "themes/toystory.png",
    "Disney": "themes/disney.png",
    "Disney Princess": "themes/disney.png",
    "Disney Series 2": "themes/disney.png",
    "SpongeBob SquarePants": "themes/spongebob.png",
    "Jurassic World": "themes/jurassicworld.png",
    "Jurassic World: Fallen Kingdom": "themes/jurassicworld.png",
    "Trolls: World Tour": "themes/trolls.png"
};

export default ThemeImages;